channels:
  - pytorch
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - _sysroot_linux-64_curr_repodata_hack=3
  - absl-py=2.1.0
  - adjusttext=1.2.0
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.4
  - aiosignal=1.3.1
  - alabaster=1.0.0
  - allpairspy=2.5.1
  - amply=0.1.6
  - anndata=0.10.8
  - annotated-types=0.7.0
  - anyio=4.4.0
  - aom=3.9.1
  - appdirs=1.4.4
  - argcomplete=3.5.0
  - argh=0.31.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - argparse-dataclass=2.0.0
  - arpack=3.9.1
  - array-api-compat=1.8
  - arrow=1.3.0
  - arviz=0.19.0
  - astor=0.8.1
  - astroid=3.2.4
  - asttokens=2.4.1
  - async-lru=2.0.4
  - atk-1.0=2.38.0
  - attrs=24.2.0
  - aws-c-auth=0.7.25
  - aws-c-cal=0.7.3
  - aws-c-common=0.9.27
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.3
  - aws-c-http=0.8.7
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.4
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.5
  - aws-sdk-cpp=1.11.379
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - babel=2.14.0
  - backoff=2.2.1
  - beautifulsoup4=4.12.3
  - bedtools=2.31.1
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - biopython=1.84
  - black=24.10.0
  - bleach=6.1.0
  - blessed=1.19.1
  - blinker=1.8.2
  - blosc=1.21.6
  - boto3=1.35.0
  - botocore=1.35.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.33.0
  - ca-certificates=2025.8.3
  - cachecontrol=0.14.0
  - cachecontrol-with-filecache=0.14.0
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2025.8.3
  - cffi=1.17.0
  - cfgv=3.3.1
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - chex=0.1.86
  - cleo=2.1.0
  - click=8.1.7
  - cloudpickle=3.1.0
  - cni=1.0.1
  - cni-plugins=1.3.0
  - coin-or-cbc=2.10.11
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.11
  - coin-or-utils=2.11.12
  - coincbc=2.10.11
  - colorama=0.4.6
  - colour=0.1.5
  - comm=0.2.2
  - conda-inject=1.3.2
  - configargparse=1.7
  - connection_pool=0.0.3
  - contextlib2=21.6.0
  - contourpy=1.2.1
  - coverage=7.6.1
  - crashtest=0.4.1
  - croniter=1.4.1
  - cryptography=43.0.0
  - cuda-cccl_linux-64=12.6.37
  - cuda-crt-dev_linux-64=12.6.20
  - cuda-crt-tools=12.6.20
  - cuda-cudart=12.6.77
  - cuda-cudart-dev=12.6.77
  - cuda-cudart-dev_linux-64=12.6.77
  - cuda-cudart-static=12.6.77
  - cuda-cudart-static_linux-64=12.6.77
  - cuda-cudart_linux-64=12.6.77
  - cuda-cupti=12.6.37
  - cuda-driver-dev_linux-64=12.6.37
  - cuda-nvcc=12.6.20
  - cuda-nvcc-dev_linux-64=12.6.20
  - cuda-nvcc-impl=12.6.20
  - cuda-nvcc-tools=12.6.20
  - cuda-nvcc_linux-64=12.6.20
  - cuda-nvrtc=12.6.20
  - cuda-nvtx=12.6.37
  - cuda-nvvm-dev_linux-64=12.6.20
  - cuda-nvvm-impl=12.6.20
  - cuda-nvvm-tools=12.6.20
  - cuda-version=12.6
  - cudnn=8.9.7.29
  - curl=8.10.1
  - custom-inherit=2.4.1
  - cycler=0.12.1
  - dash=2.18.1
  - dash-bio=1.0.2
  - dash-core-components=2.0.0
  - dash-html-components=2.0.0
  - dash-table=5.0.0
  - dateutils=0.6.12
  - datrie=0.8.2
  - dav1d=1.2.1
  - dbus=1.13.6
  - dcor=0.6
  - debugpy=1.8.5
  - decorator=5.1.1
  - decoupler=1.5.0
  - deepdiff=7.0.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - distinctipy=1.3.4
  - distlib=0.3.8
  - dm-tree=0.1.8
  - dnspython=2.6.1
  - docopt=0.6.2
  - docrep=0.3.2
  - docutils=0.21.2
  - dpath=2.2.0
  - dulwich=0.21.7
  - email-validator=2.2.0
  - email_validator=2.2.0
  - entrypoints=0.4
  - equinox=0.11.5
  - et_xmlfile=1.1.0
  - etils=1.9.2
  - exceptiongroup=1.2.2
  - execnet=2.1.1
  - executing=2.0.1
  - expat=2.6.2
  - fastapi=0.112.1
  - fastapi-cli=0.0.5
  - fastcluster=1.2.6
  - filelock=3.15.4
  - flake8=7.1.1
  - flask=3.0.3
  - flax=0.8.5
  - flit=3.9.0
  - flit-core=3.9.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - formulaic=1.0.2
  - fqdn=1.5.1
  - freetype=2.12.1
  - freetype-py=2.3.0
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - fsspec=2024.6.1
  - ftpretty=0.4.0
  - gcc_impl_linux-64=13.3.0
  - gcc_linux-64=13.3.0
  - gdk-pixbuf=2.42.12
  - geoparse=2.0.4
  - get-annotations=0.1.2
  - gffutils=0.13
  - gflags=2.2.2
  - gfortran_impl_linux-64=13.3.0
  - ghostscript=10.03.1
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.7.1
  - glpk=5.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - goatools=1.4.12
  - graphite2=1.3.13
  - graphlib-backport=1.0.3
  - graphviz=12.0.0
  - grpcio=1.62.2
  - gseapy=1.1.3
  - gsl=2.7
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx_impl_linux-64=13.3.0
  - gxx_linux-64=13.3.0
  - h11=0.14.0
  - h2=4.1.0
  - h5netcdf=1.3.0
  - h5py=3.11.0
  - harfbuzz=9.0.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.28.0
  - humanfriendly=10.0
  - humanize=4.10.0
  - hyperframe=6.0.1
  - icu=75.1
  - identify=2.6.0
  - idna=3.7
  - igraph=0.10.13
  - imagesize=1.4.1
  - immutables=0.20
  - importlib-metadata=8.3.0
  - importlib_metadata=8.3.0
  - importlib_resources=6.4.3
  - inflect=7.3.1
  - iniconfig=2.0.0
  - inquirer=3.1.4
  - interface_meta=1.3.0
  - ipdb=0.13.13
  - ipykernel=6.29.5
  - ipython=8.26.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.3
  - isoduration=20.11.0
  - isort=5.13.2
  - itsdangerous=2.2.0
  - jaraco.classes=3.4.0
  - jax=0.4.31
  - jaxlib=0.4.31
  - jaxopt=0.8.3
  - jaxtyping=0.2.22
  - jedi=0.19.1
  - jeepney=0.8.0
  - jinja2=3.1.4
  - jmespath=1.0.1
  - joblib=1.4.2
  - jq=1.7.1
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.2
  - jupyterlab_code_formatter=3.0.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - jupytext=1.16.4
  - kernel-headers_linux-64=3.10.0
  - keyring=24.3.1
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - kneed=0.8.5
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - legacy-api-wrap=1.4
  - leidenalg=0.10.2
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.5.2
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.6.0.22
  - libcufft=11.2.6.28
  - libcurand=10.3.7.37
  - libcurl=8.10.1
  - libcusolver=11.6.4.38
  - libcusparse=12.5.2.23
  - libdeflate=1.21
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-devel_linux-64=13.3.0
  - libgcc-ng=14.1.0
  - libgd=2.3.3
  - libgfortran=3.0.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.82.2
  - libgomp=14.1.0
  - libgoogle-cloud=2.28.0
  - libgoogle-cloud-storage=2.28.0
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libleidenalg=0.11.1
  - libllvm14=14.0.6
  - libmagma=2.7.2
  - libmagma_sparse=2.7.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libnvjitlink=12.6.20
  - libopenblas=0.3.27
  - libparquet=17.0.0
  - libpng=1.6.44
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librsvg=2.58.3
  - libsanitizer=13.3.0
  - libseccomp=2.4.4
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-devel_linux-64=13.3.0
  - libstdcxx-ng=14.1.0
  - libthrift=0.20.0
  - libtiff=4.7.0
  - libtorch=2.3.1
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - lightning=2.0.9.post0
  - lightning-cloud=0.5.70
  - lightning-utilities=0.11.6
  - lineax=0.0.5
  - llvm-openmp=18.1.8
  - llvmlite=0.42.0
  - loguru=0.7.2
  - loompy=3.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - make=4.3
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - matplotlib-venn=1.1.1
  - mccabe=0.7.0
  - mdit-py-plugins=0.4.1
  - mdurl=0.1.2
  - mistune=3.0.2
  - mkl=2023.2.0
  - ml-collections=0.1.1
  - ml_dtypes=0.4.0
  - more-itertools=10.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - mudata=0.3.0
  - multidict=6.0.5
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - muon=0.1.6
  - mypy_extensions=1.0.0
  - natsort=8.4.0
  - nbclassic=1.2.0
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - nbsphinx=0.9.7
  - nccl=2.22.3.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nodeenv=1.9.1
  - nodejs=22.6.0
  - notebook=7.3.1
  - notebook-shim=0.2.4
  - numba=0.59.1
  - numpy=1.26.4
  - numpy_groupies=0.11.2
  - numpyro=0.15.2
  - omnipath=1.0.8
  - oniguruma=6.9.9
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.5.2
  - opt-einsum=3.3.0
  - opt_einsum=3.3.0
  - optax=0.2.2
  - orbax-checkpoint=0.4.4
  - orc=2.0.2
  - ordered-set=4.1.0
  - orjson=3.10.7
  - ott-jax=0.4.7
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.2
  - pandoc=3.3
  - pandocfilters=1.5.0
  - pango=1.54.0
  - parmed=4.2.2
  - parse=1.20.2
  - parso=0.8.4
  - pathspec=0.12.1
  - patsy=0.5.6
  - pcre2=10.44
  - periodictable=1.7.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.2
  - pkginfo=1.11.1
  - pkgutil-resolve-name=1.3.10
  - plac=1.4.3
  - platformdirs=4.2.2
  - plotly=5.24.1
  - pluggy=1.5.0
  - ply=3.11
  - poetry=1.8.3
  - poetry-core=1.9.0
  - poetry-plugin-export=1.8.0
  - pre-commit=3.8.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - protobuf=4.25.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pubchempy=1.0.4
  - pulp=2.8.0
  - pure_eval=0.2.3
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pybind11-abi=4
  - pycairo=1.26.1
  - pycodestyle=2.12.1
  - pycparser=2.22
  - pydantic=2.1.1
  - pydantic-core=2.4.0
  - pydeseq2=0.4.10
  - pydot=3.0.1
  - pyfaidx=0.8.1.2
  - pyflakes=3.2.0
  - pygments=2.18.0
  - pyjwt=2.9.0
  - pylint=3.2.6
  - pymde=0.1.18
  - pynndescent=0.5.13
  - pynvml=11.5.3
  - pyomo=6.7.3
  - pyparsing=3.1.2
  - pypng=0.20220715.0
  - pyproject_hooks=1.1.0
  - pyro-api=0.1.2
  - pyro-ppl=1.9.1
  - pysocks=1.7.1
  - pytest=8.3.2
  - pytest-cov=5.0.0
  - pytest-xdist=3.6.1
  - python=3.11.9
  - python-build=1.2.1
  - python-dateutil=2.9.0
  - python-editor=1.0.4
  - python-fastjsonschema=2.20.0
  - python-igraph=0.11.6
  - python-installer=0.7.0
  - python-json-logger=2.0.7
  - python-multipart=0.0.9
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytorch=2.3.1
  - pytorch-lightning=2.4.0
  - pytz=2024.1
  - pyupgrade=3.17.0
  - pyvcf3=1.0.3
  - pyyaml=6.0.2
  - pyzmq=26.1.1
  - qhull=2020.2
  - qtconsole-base=5.5.2
  - qtpy=2.4.1
  - r-base=4.3.3
  - r-renv=1.0.11
  - radian=0.6.13
  - rapidfuzz=3.9.6
  - rav1e=0.6.6
  - rchitect=0.4.7
  - re2=2023.09.01
  - readchar=4.2.0
  - readline=8.2
  - referencing=0.35.1
  - regex=2024.11.6
  - reportlab=4.2.2
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - reretry=0.11.8
  - retrying=1.3.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rlpycairo=0.2.0
  - roman-numerals-py=3.1.0
  - rpds-py=0.20.0
  - rpy2=3.5.11
  - s2n=1.5.0
  - s3transfer=0.10.2
  - scanpy=1.10.2
  - scikit-learn=1.5.1
  - scikit-misc=0.1.4
  - scipy=1.14.0
  - scvi-tools=1.1.6
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - secretstorage=3.3.3
  - sed=4.8
  - send2trash=1.8.3
  - session-info=1.0.0
  - setuptools=72.2.0
  - shap=0.46.0
  - shellingham=1.5.4
  - simplegeneric=0.8.1
  - simplejson=3.19.3
  - singularityce=3.9.5
  - six=1.16.0
  - skranger=0.8.0
  - sleef=3.6.1
  - slicer=0.0.8
  - smart_open=7.0.4
  - smmap=5.0.0
  - snakefmt=0.10.2
  - snakemake-executor-plugin-slurm=0.9.0
  - snakemake-executor-plugin-slurm-jobstep=0.2.1
  - snakemake-interface-common=1.17.3
  - snakemake-interface-executor-plugins=9.2.0
  - snakemake-interface-report-plugins=1.0.0
  - snakemake-interface-storage-plugins=3.3.0
  - snakemake-minimal=8.18.1
  - snappy=1.2.1
  - sniffio=1.3.1
  - snowballstemmer=2.2.0
  - soupsieve=2.5
  - sparse=0.15.4
  - sparsecca=0.3.1
  - sphinx=8.2.3
  - sphinx-autodoc-typehints=3.1.0
  - sphinx-copybutton=0.5.2
  - sphinx_rtd_theme=3.0.1
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jquery=4.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-programoutput=0.18
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - squashfs-tools=4.6.1
  - stack_data=0.6.2
  - starlette=0.38.2
  - starsessions=1.3.0
  - statsmodels=0.14.2
  - stdlib-list=0.10.0
  - stopit=1.1.2
  - svt-av1=2.1.2
  - sympy=1.13.2
  - sysroot_linux-64=2.17
  - tabulate=0.9.0
  - tbb=2021.12.0
  - tenacity=9.0.0
  - tensorboard=2.17.1
  - tensorboard-data-server=0.7.0
  - tensorstore=0.1.62
  - terminado=0.18.1
  - texttable=1.7.0
  - threadpoolctl=3.5.0
  - throttler=1.2.2
  - tinycss2=1.3.0
  - tk=8.6.13
  - tktable=2.10
  - tokenize-rt=6.0.0
  - toml=0.10.2
  - tomli=2.0.1
  - tomli-w=1.0.0
  - tomlkit=0.13.2
  - toolz=0.12.1
  - toposort=1.10
  - torchmetrics=1.4.0.post0
  - torchtriton=2.3.1
  - torchvision=0.18.1
  - tornado=6.4.1
  - toyplot=1.0.3
  - toytree=3.0.4
  - tqdm=4.66.5
  - traitlets=5.14.3
  - trove-classifiers=2024.7.2
  - typeguard=4.3.0
  - typer=0.12.4
  - typer-slim=0.12.4
  - typer-slim-standard=0.12.4
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024a
  - tzlocal=5.2
  - ukkonen=1.0.1
  - umap-learn=0.5.6
  - uri-template=1.3.0
  - urllib3=2.2.2
  - uvicorn=0.30.6
  - virtualenv=20.26.3
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=12.0
  - werkzeug=3.0.3
  - wheel=0.44.0
  - widgetsnbextension=4.0.11
  - wrapt=1.16.0
  - xarray=2024.7.0
  - xarray-einstats=0.7.0
  - xlsxwriter=3.2.0
  - xmltodict=0.13.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - yq=3.4.3
  - yte=1.5.4
  - zeromq=4.3.5
  - zipp=3.20.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - awesome-slugify==1.6.5
      - blitzgsea==1.3.45
      - dynamictreecut==0.1.1
      - keggutils==0.4.0
      - lamin-utils==0.13.2
      - opencv-python==4.10.0.84
      - pertpy==0.8.0
      - scperturb==0.1.0
      - unidecode==0.04.21
